/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static jdbc.JdbcConnection.getConnection;

/**
 *
 * @author Asus
 */
public class RentCars extends javax.swing.JFrame {

    /**
     * Creates new form RentCars
     */
    public RentCars() {
        initComponents();
        loadCarList();
    }
    
        private void loadCarList(){
        DefaultTableModel model = (DefaultTableModel) tablecars.getModel();
        model.setRowCount(0);
        try (Connection con = getConnection();
               java.sql.Statement st = con.createStatement();
               ResultSet rs = st.executeQuery("SELECT * FROM cars")) {
            
         
            while (rs.next()) {
                
               String id = rs.getString("ID");
               String plate = rs.getString("Plate_No");
               String brand = rs.getString("Brand");
               String models = rs.getString("Model");
               int year = rs.getInt("Year");
               double price = rs.getDouble("Price");
               String status = rs.getString("Status");
             model.addRow(new Object[] {id, plate,brand,models,year,price,status});
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to show Car List");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablecars = new javax.swing.JTable();
        rentcar = new javax.swing.JButton();
        returncar = new javax.swing.JButton();
        dash = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        tablecars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Plate_No", "Model", "Brand", "Year", "Price", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablecars);

        rentcar.setText("Rent Vehicle");
        rentcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentcarActionPerformed(evt);
            }
        });

        returncar.setText("Return Vehicle");
        returncar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returncarActionPerformed(evt);
            }
        });

        dash.setText("jButton1");
        dash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(rentcar)
                        .addGap(54, 54, 54)
                        .addComponent(returncar)
                        .addGap(65, 65, 65)
                        .addComponent(dash)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentcar)
                    .addComponent(returncar)
                    .addComponent(dash))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rentcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentcarActionPerformed
          DefaultTableModel model = (DefaultTableModel) tablecars.getModel();
        int selected = tablecars.getSelectedRow();
       if (selected == -1) {
           JOptionPane.showMessageDialog(this, "Please Select a Car to rent.");
           return;
       }
        
       String status = model.getValueAt(selected, 6).toString();
        if (!status.equals("Available")) {
            JOptionPane.showMessageDialog(this, "Car is not available.");
            return;
        }
         if (status.equalsIgnoreCase("Not Available")) {
           JOptionPane.showMessageDialog(this, "The car is already rented");
           return;
        }
         String plates = model.getValueAt(selected, 1).toString();
        double pricePerDay = Double.parseDouble(model.getValueAt(selected, 5).toString());
        double total = pricePerDay * MainFrame.rentaldays;
       
        try (Connection con = getConnection();
                PreparedStatement ps = con.prepareStatement("UPDATE cars SET Status = 'Not Available' WHERE Plate_No =?")) {
                ps.setString(1, plates);
                ps.executeUpdate();
                
                
                
                PreparedStatement ps2 = con.prepareStatement("INSERT INTO rentals (Client_Name, Plate_No, Rental_Days, Total) VALUES (?, ?, ?, ?)");
                 ps2.setString(1, MainFrame.name);
                 ps2.setString(2, plates);
                 ps2.setInt(3, MainFrame.rentaldays);
                 ps2.setDouble(4, total);
                 ps2.executeUpdate();
                 
                 String receipt = "==== VEHICLE RENTAL RECEIPT ====\n"
                       + "Client Name: " + MainFrame.name + "\n"
                       + "Plate No: " + plates + "\n"
                       + "Rental Days: " + MainFrame.rentaldays + "\n"
                       + "Price per Day: ₱" + pricePerDay + "\n"
                       + "-----------------------------\n"
                       + "Total: ₱" + total + "\n"
                       + "==============================";

                JOptionPane.showMessageDialog(this, receipt, "receipt", JOptionPane.INFORMATION_MESSAGE);
                loadCarList();
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to update car status.");
        }
                                    
                                    

    }//GEN-LAST:event_rentcarActionPerformed

    private void returncarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returncarActionPerformed
       int row = tablecars.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a car to return.");
        return;
    }

    String status = tablecars.getValueAt(row, 6).toString();
    if (status.equalsIgnoreCase("Available")) {
        JOptionPane.showMessageDialog(this, "This car is not currently rented.");
        return;
    }

    String plate = tablecars.getValueAt(row, 1).toString();

    try (Connection con = getConnection()) {
        PreparedStatement ps = con.prepareStatement("UPDATE cars SET Status = 'Available' WHERE Plate_No = ?");
        ps.setString(1, plate);
        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Car returned successfully.");
        loadCarList(); // Refresh table

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error during return.");
    }

    }//GEN-LAST:event_returncarActionPerformed

    private void dashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashActionPerformed
       DashBoard db = null;
        try {
            db = new DashBoard();
        } catch (SQLException ex) {
            Logger.getLogger(RentCars.class.getName()).log(Level.SEVERE, null, ex);
        }
       db.setVisible(true);
       dispose();
    }//GEN-LAST:event_dashActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentCars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dash;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rentcar;
    private javax.swing.JButton returncar;
    private javax.swing.JTable tablecars;
    // End of variables declaration//GEN-END:variables
}
